from random import *
lijst = [5,12,19,27,3]
lijst.append(25)
print(lijst)
print(f'Er zitten {len(lijst)} elementen in de lijst.')
lijst.remove(lijst[1])
cijfer = lijst.pop(0)
print(f'Het nummer {cijfer} is verwijderd')
lijst.insert(0,36)
print(lijst)
print(f'Het totaal van de lijst is {sum(lijst)}')
lijst.clear()
print(lijst)
for i in range(0,5): lijst.insert(i,i+1)
print(lijst)
lijst.append(randint(1,10))
lijst.append(randint(50,100))
print(lijst)
print(f'Er nu zitten {len(lijst)} elementen in de lijst en het totaal van de lijst is {sum(lijst)}')
print(f'De index vann de waarde 25 is {lijst(25)}')